name: 'Cross-Repo Sync'
description: 'Syncs and renames files or folders from your repo to a different repository and branch'
author: 'github-actions[bot]'

branding:
  icon: 'git-merge'
  color: 'blue'

inputs:
  personal_access_token:
    description: 'A Personal Access Token (PAT) with repo scope to allow pushing to the destination repository. The default GITHUB_TOKEN will not work for pushing to other repos. Required scopes: repo, workflow (if syncing workflow files).'
    required: true
  sync_paths:
    description: 'A multi-line string of source and destination mappings. Use a colon (:) to separate the source from the destination (e.g., src/docs:content/docs). Each mapping must be on its own line. If no destination is given (e.g., README.md), the source is copied to the root of the destination repo. Supports quoted paths for spaces.'
    required: true
  destination_repo:
    description: 'The target repository in owner/repo format. Example: microsoft/vscode'
    required: true
  dry_run:
    description: 'Run in dry-run mode without making actual changes. Useful for testing.'
    required: false
    default: 'false'

outputs:
  commit_hash:
    description: 'The full git hash of the new commit in the destination repository. Empty if no changes were pushed.'

runs:
  using: 'composite'
  steps:
  - name: Debug
    shell: bash
    run: |
      echo "**** env ****"
      env
      echo "**** env end ****"

      echo
      echo 

      echo "Inputs:"
      echo "  personal_access_token: ${{ inputs.personal_access_token }}"
      echo "  sync_paths: ${{ inputs.sync_paths }}"
      echo "  destination_repo: ${{ inputs.destination_repo }}"
      echo "  dry_run: ${{ inputs.dry_run }}"

  - name: Install Dependencies
    working-directory: ${{ github.action_path }}
    run: yarn
    shell: bash

  - name: Run Action Logic
    run: node --experimental-strip-types ${{ github.action_path }}/src/main.ts
    shell: bash
